Fixed tests for api-explorer and try-it
- `yarn build` works
- `yarn test` works in both package folders
- I haven't removed what *should* now be redundant jest config files from `api-explorer` and `try-it`
- Had to adjust some codegen tests again because cherry picking didn't capture them
- Getting this strange result but it's now the only failing test with `yarn test` from the repo root:

``` PASS  packages/try-it/src/components/RequestForm.spec.tsx
     ● Console

       console.error
         Error: Not implemented: HTMLFormElement.prototype.submit
             at module.exports (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
             at HTMLFormElementImpl.submit (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:77:5)
             at HTMLFormElementImpl._doSubmit (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:69:10)
             at HTMLButtonElementImpl._activationBehavior (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLButtonElement-impl.js:23:14)
             at HTMLButtonElementImpl._dispatch (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:26)
             at HTMLButtonElementImpl.dispatchEvent (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
             at HTMLButtonElement.dispatchEvent (/Users/looker/sdk-codegen/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
             at /Users/looker/sdk-codegen/node_modules/@testing-library/dom/dist/events.js:25:20
             at /Users/looker/sdk-codegen/node_modules/@testing-library/react/dist/pure.js:65:16
             at batchedUpdates$1 (/Users/looker/sdk-codegen/node_modules/react-dom/cjs/react-dom.development.js:21856:12) undefined

         at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
         at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
         at HTMLFormElementImpl.submit (node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:77:5)
         at HTMLFormElementImpl._doSubmit (node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:69:10)
         at HTMLButtonElementImpl._activationBehavior (node_modules/jsdom/lib/jsdom/living/nodes/HTMLButtonElement-impl.js:23:14)
         at HTMLButtonElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:26)
         at HTMLButtonElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
```